# Generated by Django 4.2.15 on 2024-08-31 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_alter_reservation_created_by_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservation',
            options={'ordering': ['-created_on']},
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='created_at',
            new_name='created_on',
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='updated_at',
            new_name='updated_on',
        ),
    ]
