# Generated by Django 4.2.15 on 2024-09-08 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_alter_reservation_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='guest_count',
            field=models.PositiveIntegerField(),
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_number', models.IntegerField(unique=True)),
                ('zone', models.IntegerField()),
                ('capacity', models.IntegerField()),
                ('vip_category', models.IntegerField(choices=[(1, 'Standard'), (2, 'Premium'), (3, 'VIP')])),
                ('is_quiet', models.BooleanField(default=False)),
                ('is_outside', models.BooleanField(default=False)),
                ('has_bench_seating', models.BooleanField(default=False)),
                ('has_disabled_access', models.BooleanField(default=False)),
                ('note', models.CharField(blank=True, max_length=255, null=True)),
                ('adjacent_tables', models.ManyToManyField(blank=True, to='booking.table')),
            ],
        ),
        migrations.AddField(
            model_name='reservation',
            name='tables',
            field=models.ManyToManyField(to='booking.table'),
        ),
    ]
