# Generated by Django 4.2.15 on 2024-09-09 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_reservation_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='preference',
            field=models.IntegerField(choices=[(0, 'No Preference'), (1, 'Quiet'), (2, 'Not Quiet')], default=0),
        ),
    ]
