# Generated by Django 4.2.15 on 2024-09-09 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_reservation_preference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='preference',
            field=models.IntegerField(choices=[(0, 'No Preference'), (1, 'True'), (2, 'False')], default=0),
        ),
    ]
