# Generated by Django 4.2.15 on 2024-09-14 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0010_alter_reservation_has_bench_seating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='has_bench_seating',
            field=models.CharField(choices=[('no_preference', 'No Preference'), ('yes', 'Yes'), ('no', 'No')], default='no_preference', max_length=20),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='has_disabled_access',
            field=models.CharField(choices=[('no_preference', 'No Preference'), ('yes', 'Yes'), ('no', 'No')], default='no_preference', max_length=20),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='is_outside',
            field=models.CharField(choices=[('no_preference', 'No Preference'), ('yes', 'Yes'), ('no', 'No')], default='no_preference', max_length=20),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='is_quiet',
            field=models.CharField(choices=[('no_preference', 'No Preference'), ('yes', 'Yes'), ('no', 'No')], default='no_preference', max_length=20),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='preference',
            field=models.IntegerField(choices=[('no_preference', 'No Preference'), ('yes', 'Yes'), ('no', 'No')], default=0),
        ),
    ]
