# Generated by Django 4.2.15 on 2024-09-14 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0011_alter_reservation_has_bench_seating_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='preference',
        ),
    ]
