# Generated by Django 4.2.15 on 2024-09-20 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0014_sitesettings_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='phone_number',
            field=models.CharField(default='0000000000', max_length=15),
        ),
    ]
