# Generated by Django 4.2.15 on 2024-09-22 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0016_openingtime_reservationtimespan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='openingtime',
            name='day_of_week',
            field=models.CharField(choices=[('mon', 'Monday'), ('tue', 'Tuesday'), ('wed', 'Wednesday'), ('thu', 'Thursday'), ('fri', 'Friday'), ('sat', 'Saturday'), ('sun', 'Sunday')], max_length=3),
        ),
    ]
