# Generated by Django 4.2.15 on 2024-09-22 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0017_alter_openingtime_day_of_week'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservationtimespan',
            old_name='party_size',
            new_name='guest_count',
        ),
    ]
