# Generated by Django 4.2.15 on 2024-09-22 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0018_rename_party_size_reservationtimespan_guest_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='reservation_end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
