# Generated by Django 4.2.15 on 2024-09-22 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0019_reservation_reservation_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='openingtime',
            name='close_time',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='openingtime',
            name='open_time',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
