# Generated by Django 4.2.15 on 2024-09-22 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0020_alter_openingtime_close_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='openingtime',
            name='close_time',
            field=models.TimeField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='openingtime',
            name='open_time',
            field=models.TimeField(default=0),
            preserve_default=False,
        ),
    ]
