# Generated by Django 4.2.15 on 2024-09-22 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0021_alter_openingtime_close_time_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OpeningTime',
            new_name='OpeningTime',
        ),
    ]
