# Generated by Django 4.2.15 on 2024-09-22 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0022_rename_openingtime_openingtime2'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpeningTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(choices=[('mon', 'Monday'), ('tue', 'Tuesday'), ('wed', 'Wednesday'), ('thu', 'Thursday'), ('fri', 'Friday'), ('sat', 'Saturday'), ('sun', 'Sunday')], max_length=3)),
                ('open_time', models.TimeField()),
                ('close_time', models.TimeField()),
            ],
            options={
                'verbose_name': 'Opening Time',
                'verbose_name_plural': 'Opening Times',
                'ordering': ['day_of_week'],
            },
        ),
    ]
